### ISSUE TITLE
[feature request] Original Data for Lexicon Dictionaries

### ISSUE THREAD

**Issue by quantdev05** [socius-org/socscikit#1]
Hi, 

Is it possible to retrieve original data for lexicon dictionaries? 

I would like to see how they look like before they are processed. 

Thanks!

**Comment by nick-sh-oh** [comment]
Hi @quantdev05, 

Thanks for your suggestion. 

I just added a new function `load_origin` in `socscikit.CompliSent.lexicon`. The function returns the original lexicon dictionary as a pandas DataFrame. 

Also don't forget to upgrade socscikit package using `pip install --upgrade socscikit`! 

Best,
Nick

**Comment by quantdev05** [comment]
Hi @nick-sh-oh, 

I upgraded socscikit, but there is an error when I used `from socscikit import CompliSent`. 

The error looks like 

`---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Input In [1], in <cell line: 1>()
----> 1 from socscikit import CompliSent

File ~\Anaconda3\lib\site-packages\socscikit\__init__.py:1, in <module>
----> 1 from socscikit import CompliSent

File ~\Anaconda3\lib\site-packages\socscikit\CompliSent.py:3, in <module>
      1 import os 
      2 import pickle 
----> 3 from socscikit.utils import CS 
      5 class lexicon:
      6     def __init__(self): 

File ~\Anaconda3\lib\site-packages\socscikit\utils.py:10, in <module>
      8 from spacymoji import Emoji
      9 import re
---> 10 from socscikit.lexicon_dictionary import emos
     13 class CS:
     14     def __init__(self):

ModuleNotFoundError: No module named 'socscikit.lexicon_dictionary'`

**Comment by nick-sh-oh** [comment]
Hi @quantdev05 , 

The `ModuleNotFoundError` has been fixed! Please reinstall/upgrad `socscikit`, and if there are any further issues, please do not hesistate to reach out! 

Best,
Nick
