### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by quantdev05** [socius-org/socscikit#2]
Hi, 

I am getting the following error - FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\nicks\\Anaconda3\\lib\\site-packages\\socscikit\\dict_arXiv\\Aigents\\Aigents+_v2022.csv' 

Would you mind giving it a look?

**Comment by nick-sh-oh** [comment]
Hi @quantdev05,

Thanks for point it out! I just realised there was an issue when uploading the package in PyPi. 

The error has been fixed, everything should work fine by now.

Best,
Nick
